legal_code/citas/urls.py
from django.urls import path
from . import views

# Las URLs de la aplicación citas que luego se incluirán en las URLs globales del proyecto

urlpatterns = [
    path('', views.citas_principal, name='citas-principal'),
    path('agendar-cita/', views.agendar_cita, name='agendar-cita'),
    path('agendar-cita/<int:id_profesional>/', views.agendar_cita, name='agendar-cita-info-profesional')
]

legal_code/core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

"""
En este array se almacenan las rutas que tendremos disponibles
En la aplicación. En cada una de ellas se establecen las relaciones 
con la vista creada para mostrar las plantillas en el fichero
views.py

"""

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('especialidad/<slug:filtro_especialidad>/', views.homepage, name='homepage_filtered'),
    path('subespecialidad/<slug:filtro_subespecialidad>/', views.homepage, name='homepage_double_filtered'),
    path('logout/', views.salir, name='salir'),
    path('register/', views.register, name='register'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre-nosotros'),
    path('calendario/', views.calendario, name='calendario'),
    path('solicitudes/', views.solicitudes, name='solicitudes'),
    path('obtener-citas/', views.obtener_citas, name='obtener_citas'),
    path('anular-cita/<int:id_cita>/', views.anular_cita, name='anular_cita'),
    path('politica-cancelaciones/', views.politica_cancelaciones, name='politica_cancelaciones'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

legal_code/legal_code/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

# Estas son las rutas que se van a usar en la aplicación. Se incluyen las rutas de los módulos core, citas, users y las rutas de autenticación de Django.

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('citas/', include('citas.urls')),
    path('users/', include('users.urls')),
]

# Esto es simplemente una barra para debuguear la página.

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

legal_code/citas/models.py
from django.db import models
from core.models import Profesional # Importamos los modelos de la aplicación 'core' para usar Profesional
from users.models import Cliente

class Cita(models.Model):
    """
        Este modelo establece los campos de Cita y las opciones del estado en el que pueden estar.
    """
    OPCIONES_ESTADO = (
        ('P', 'PENDIENTE'),
        ('E', 'ESPERA'),
        ('C', 'CANCELADA')
    )
    
    profesional = models.ForeignKey(Profesional, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha_cita = models.DateTimeField(null=False)
    precio = models.FloatField(null=False)
    estado = models.CharField(max_length=1, null=False, choices=OPCIONES_ESTADO)
    descripcion = models.TextField(max_length=400, null=True, default='')

    def __str__(self):
        return self.cliente.name + ' - ' + self.estado

legal_code/citas/forms.py
from django import forms
from .models import Cita

class CitaForm(forms.ModelForm):
    '''
        Este formulario se utiliza para crear nuevas citas. Contiene campos para la descripción de la cita y la fecha de la cita.
    '''

    class Meta:
        model = Cita
        fields = ['descripcion', 'fecha_cita']
        
        labels = {
            'descripcion': 'Motivo de la cita: ',
            'fecha_cita': 'Fecha de la cita: ',
        }

        widgets = {
            'descripcion': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Describe brevemente el motivo de la cita...'}),
            'fecha_cita': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

legal_code/citas/views.py
from datetime import timedelta
from django.shortcuts import render, redirect
from .models import Cita
from django.contrib.auth.decorators import login_required
from .forms import CitaForm
from django.contrib import messages
from core.models import Profesional
from django.utils import timezone

@login_required
def citas_principal(request):
    """
        Esta función requiere de estar logueado y su función es obtener una 
        lista de las citas del usuario y pasarlas como contexto a la template.
        
        Args:
            request: representa la petición HTTP recibida por el servidor.
    """
    citas = Cita.objects.filter(cliente_id=request.user.id)

    data = {
        'citas': citas,
    }

    return render(request, 'citas_principal.html', data)

@login_required
def agendar_cita(request, id_profesional = None):
    """
        Esta función requiere estar logueado y sirve para agendar una cita con un pro-
        fesional. Dependiendo de si se entra a este formulario a través del link del
        navbar o a través de una card de las ofertas, el campo de profesional estará vacío
        o con el profesional de la card precargado. Comprueba que la fecha esté libre y el 
        profesional también y añade la cita a la base de datos.

        Args:
            request: representa la petición HTTP recibida por el servidor.
            id_profesional: Puede ser None. Representa el ID del profesional para la cita.
        
        Returns:  
            render: Renderizado del HTML que contiene el formulario de Citas.
    """

    if id_profesional:
        # Recuperamos el profesional para agendar la cita.
        profesional = Profesional.objects.filter(id=id_profesional)

    if request.method == 'POST':
        form = CitaForm(request.POST)

        # Esto lo obtenemos para asegurarnos de que esa fecha y ese profesional estén disponibles.
        fecha_cita = request.POST['fecha_cita']
        # profesional = request.POST['profesional']
        profesional = Profesional.objects.get(id = id_profesional)

        cita_existe = Cita.objects.filter(fecha_cita=fecha_cita, profesional=profesional).exists()

        if cita_existe:
            form = CitaForm()
            return render(request, 'agendar_cita.html', {'error': f'{profesional} no tiene esa fecha disponible. Inténtelo con otra!', 'form': form})
        else:
            if form.is_valid():
                # Cuando ponemos commit=False no añadimos la cita a la base de datos, se crea una instancia que 
                # luego modificaremos según los valores que querramos que tenga. 
                cita = form.save(commit=False)
                # Comprobamos la fecha de la cita
                if cita.fecha_cita < timezone.now() + timedelta(days=2):
                    form = CitaForm()
                    return render(request, 'agendar_cita.html', {'error': 'La cita debe pedirse con al menos 2 días de antelación. Pruebe con otra fecha!', 'form': form})
                # Guardamos el id del profesional que tiene la sesión iniciada.
                cita.profesional_id = profesional.id
                # Guardamos el id del cliente que tiene la sesión iniciada.
                cita.cliente = request.user
                # Aquí obtenemos el precio del profesional seleccionado. Cada profesional tiene un precio por
                # consulta preestablecido en su registro de la base de datos. El usuario no puede cambiarlo.
                profesional_cita = profesional
                cita.precio = profesional_cita.precio_consulta
                # Por último, establecemos el estado en PENDIENTE, que significa que se ha aceptado y se espera
                # al día de la cita. Más adelante se puede CANCELAR o poneerla en ESPERA.
                cita.estado = 'P'
                # Guardamos en la base de datos y enviamos un mensaje flash al homepage para 
                # advertir al usuario de que la cita se agendó con éxito.
                form.save()
                messages.success(request, 'La cita se ha reservado correctamente. Nos vemos muy pronto!')
                return redirect('homepage')
    else:
        if id_profesional is not None:
            profesional = Profesional.objects.get(id=id_profesional)
            form = CitaForm(initial={'profesional':profesional})
        else:
            form = CitaForm()

    data = {
        'form': form,
        'profesional': profesional
    }

    return render(request, 'agendar_cita.html', data)

legal_code/citas/templates/agendar_cita.html
{% extends "core/base.html" %}
{% block title %}
Agendar Cita
{% endblock %}

{% load tz %} <!-- Importar la zona horaria -->
{% load i18n %} <!-- Importar la internacionalización -->

{% load crispy_forms_tags %}

{% block content %}

<section class="border-top border-secondary">
    <h1 class="bg-dark text-light text-center p-3">RESERVA TU CITA AHORA!</h1>
</section>

{% language 'es' %} <!-- Establecer el idioma en español -->

<!-- Aviso sobre el motivo de la cita -->
<div id="advertencia-citas" class="container mt-3">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Aviso</h4>
        <p>Porfavor, sea claro y conciso con el motivo de la cita. El profesional valorará la viabilidad
            de la consulta y tendrá el derecho de aceptarla o rechazarla. En cualquier caso se le informará
            mediante su correo electrónico.
        </p>
        <hr>
        <p class="mb-0">Si solamente quiere obtener información, envíe un email a: <a
                href="mailto:{{profesional.email}}" class="text-dark">{{profesional.email}}</a></p>
    </div>
</div>

{% if error %}
<div id="error-time" class="container mt-3 text-center">
    <div class="alert alert-danger" role="alert">
        <p>
            {{ error }}
        </p>
    </div>
</div>
{% endif %}

<!-- Formulario para agendar una cita -->

<form method='POST' class="container mt-3">
    {% csrf_token %}

    <div class="card">
        <h2 class="card-title bg-dark text-light p-3 rounded-top text-center">Cita con:
            {{profesional.nombre}}
            {{profesional.apellidos}}</h2>
        <div class="card-body">

            {{ form | crispy }}

            <div class="row mb-3">
                <h5 class="col-6 text-end">Precio Consulta:</h5>
                <h5 class="col-6">{{profesional.precio_consulta}}€</h5>
            </div>

            <div class="row">
                <input class="btn btn-dark float-end col-12" type="submit" value="Reservar">
            </div>
        </div>
    </div>
</form>

<br>

{% endlanguage %}

{% endblock %}

legal_code/citas/templates/citas_principal.html
{% extends "core/base.html" %}
{% block title %}
Mis Citas
{% endblock %}

{% load tz %} <!-- Importar la zona horaria -->
{% load i18n %} <!-- Importar la internacionalización -->

{% load static %}

{% block content %}

<section class="border-top border-secondary">
    <h1 class="bg-dark text-light text-center p-3">Mis citas</h1>
</section>

{% language 'es' %} <!-- Establecer el idioma en español -->

<!-- Cargamos los mensajes flash que enviamos en otras peticiones si los hay -->

{% if messages %}
{% for message in messages %}
<section class="container-fluid text-center alert alert-{{ message.tags }}">
    {{ message }}
</section>
{% endfor %}
{% endif %}

<!-- Advertencia sobre cancelaciones -->

<div id="advertencia" class="container mt-3 mb-5">
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Advertencia</h4>
        <p>Recuerde! Cualquier cancelación está sujeta a las condiciones establecidas por los profesionales. En caso de
            no especificarse nada, el período de cancelación
            gratuita es de 48 horas antes de la consulta.
        </p>
        <hr>
        <p class="mb-0">Términos y condiciones de cancelación: <a href="{% url 'politica_cancelaciones' %}"
                class="text-dark text-decoration-none"><strong>Ver
                    enlace</strong></a></p>
    </div>
</div>

<!-- En caso de que existan citas para el usuario -->

{% if citas %}

<div class="accordion container mt-3">
    {% for cita in citas %}
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#cita{{cita.id}}">
                {{cita.profesional.nombre}} {{cita.profesional.apellidos}} -
                {{cita.fecha_cita}}<br>{{cita.profesional.campo}}
            </button>
        </h2>
        <div id="cita{{cita.id}}" class="accordion-collapse collapse show row mb-3" data-bs-parent="#cita{{cita.id}}">
            <div class="accordion-body col-8">
                <p><strong>Motivo de la cita: </strong>{{cita.descripcion}}</p>
                <p><strong>Especialidades:</strong>
                <ul class="list-group">{% for especialidad in cita.profesional.especialidad.all %}
                    <li class="list-group-item">{{especialidad | capfirst}}</li>
                    {% endfor %}
                </ul>
                </p>
            </div>
            <div class="col-4 mt-3">
                <strong>Precio: {{cita.precio}}€</strong><br>
                <strong>Estado: {{cita.get_estado_display}}</strong>
                <form method="post" action="{% url 'anular_cita' cita.id %}" class="text-center">
                    {% csrf_token %}
                    <div class="alert alert-danger mt-3 m" role="alert">
                        <span>Si tiene cualquier problema con la cita o desea anularla pulse en el siguiente
                            botón:</span><br>
                        <button class="btn btn-danger mt-3">Anular Cita</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- En caso de que no existan citas para el usuario -->

    {% else %}
    <section class="container">
        <div class="row">
            <img src="{% static 'img/imagenCitas2.svg' %}" class="img-fluid col-4" alt="Imagen graciosa citas">
            <div class="container-fluid full-height d-flex justify-content-center align-items-center col-8">
                <div class="col-8 d-flex flex-column align-items-center">
                    <h4 class="text-center fs-1 fs-lg-5">Actualmente no hay ninguna cita activa</h4>
                    <div class="container text-center mt-3">
                        <a href="{% url 'homepage' %}" class="btn btn-success">Ver profesionales</a><br>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endif %}
    {% endlanguage %}

    {% endblock %}